"""
Generate product_embeddings.sql with pgvector UPDATE statements — fully offline.

Reads the product (name, description) rows from setup_hosted.sql, computes an
all-MiniLM-L6-v2 (384-dim) embedding for each description, and writes UPDATE
statements that set products.embedding, matched by product name. Paste the
resulting demo/product_embeddings.sql into the Supabase SQL editor (or run it
via psql) — NO database connection is needed from this machine, so it sidesteps
every IPv6 / pooler / TLS networking problem.

    python demo/generate_embedding_sql.py
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# Use the locally-cached model — no Hugging Face network access (offline).
# The model is shared with the FAISS schema index and lives in the default HF
# cache. Set QUERYBENCH_ALLOW_HF_DOWNLOAD=1 to permit an online fetch instead.
if os.getenv("QUERYBENCH_ALLOW_HF_DOWNLOAD") != "1":
    os.environ.setdefault("HF_HUB_OFFLINE", "1")
    os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

DEMO_DIR = Path(__file__).resolve().parent
SETUP_SQL = DEMO_DIR / "setup_hosted.sql"
OUT_SQL = DEMO_DIR / "product_embeddings.sql"

# Capture ('name', 'description', price) tuples from the products VALUES block.
ROW_RE = re.compile(r"\(\s*'((?:[^']|'')*)'\s*,\s*'((?:[^']|'')*)'\s*,\s*[0-9.]+\s*\)")


def sql_unescape(value: str) -> str:
    return value.replace("''", "'")


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def main() -> int:
    text = SETUP_SQL.read_text(encoding="utf-8")

    # Only parse the products INSERT block to avoid matching unrelated tuples.
    marker = "INSERT INTO products (name, description, price)"
    idx = text.find(marker)
    if idx == -1:
        print(f"ERROR: could not find products INSERT in {SETUP_SQL}", file=sys.stderr)
        return 2
    block = text[idx:]
    end = block.find(";")
    if end != -1:
        block = block[:end]

    rows = ROW_RE.findall(block)
    if not rows:
        print("ERROR: no product rows parsed.", file=sys.stderr)
        return 2

    products = [(sql_unescape(n), sql_unescape(d)) for n, d in rows]
    print(f"Parsed {len(products)} products from setup_hosted.sql.")

    try:
        from sentence_transformers import SentenceTransformer  # type: ignore
    except ImportError as exc:
        print(f"ERROR: sentence-transformers not installed: {exc}", file=sys.stderr)
        return 2

    print("Loading embedding model (all-MiniLM-L6-v2, offline cache)...")
    try:
        model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    except Exception as exc:
        print(
            "ERROR: could not load the cached embedding model: "
            f"{exc}\nThe model must have been downloaded once while online. "
            "To force an online download re-run with QUERYBENCH_ALLOW_HF_DOWNLOAD=1.",
            file=sys.stderr,
        )
        return 2

    lines = [
        "-- Generated by demo/generate_embedding_sql.py - pgvector product embeddings.",
        "-- Paste into the Supabase SQL editor (or run via psql) to populate",
        "-- products.embedding. Safe to re-run (idempotent UPDATE by name).",
        "BEGIN;",
    ]
    for name, description in products:
        vec = model.encode([description], show_progress_bar=False)[0]
        literal = "[" + ",".join(repr(float(x)) for x in vec) + "]"
        lines.append(
            f"UPDATE products SET embedding = '{literal}'::vector "
            f"WHERE name = '{sql_escape(name)}';"
        )
    lines.append("COMMIT;")
    lines.append(
        "-- Verify: SELECT count(*) FROM products WHERE embedding IS NOT NULL;"
        f"  -- expect {len(products)}"
    )

    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_SQL} ({len(products)} UPDATE statements).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
